# Generated by Django 2.1.1 on 2018-09-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
