# Generated by Django 2.1.1 on 2018-09-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_interview_create_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='hostname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='interview',
            name='method',
            field=models.IntegerField(default=1),
        ),
    ]
