# Generated by Django 2.1.1 on 2018-09-01 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_auto_20180902_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='hostname',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='interface.HostName'),
            preserve_default=False,
        ),
    ]
